common: prplmesh_utils.sh: add bml execute func
This is a preparative commit for "common: prplmesh_utils.sh: use BML for
operational check"

Add execute BML function

Signed-off-by: itay elenzweig <itayx.elenzweig@intel.com>

diff --git a/common/beerocks/scripts/prplmesh_utils.sh.in b/common/beerocks/scripts/prplmesh_utils.sh.in
--- a/common/beerocks/scripts/prplmesh_utils.sh.in
+++ b/common/beerocks/scripts/prplmesh_utils.sh.in
@@ -246,6 +246,17 @@ stop_function() {
     [ "$DELETE_LOGS" = "true" ] && prplmesh_delete_logs
 }
 
+execute_beerocks_command() {
+    dbg "Executing beerocks cli command: $*"
+    if [ -e $PRPLMESH_BIN_DIR/beerocks_cli ]; then
+        output=$(${PRPLMESH_BIN_DIR}/beerocks_cli -c "$@")
+        return $?
+    else
+        err "BML CLI not found"
+        return 1
+    fi
+}
+
 # Note: Apparently on some Linux version space is added to the process name.
 # Therefore added "($|[[:blank:]])" to the end of the regex expression which means the end of the
 # line ($) or blank character ([[:blank:]])
