fixup! WIP: added travis CI testing for prplmesh
Signed-off-by: Ostap <slyusar.ostap@gmail.com>

diff --git a/common/beerocks/scripts/prplmesh_utils.sh.in b/common/beerocks/scripts/prplmesh_utils.sh.in
--- a/common/beerocks/scripts/prplmesh_utils.sh.in
+++ b/common/beerocks/scripts/prplmesh_utils.sh.in
@@ -102,7 +102,10 @@ status_function() {
 
 check_function() {
     echo "$0: check"
-    cat "/tmp/$USER/beerocks/logs/beerocks_agent.log" |grep 'CONNECTED --> OPERATIONAL'
+    if ! grep -q 'CONNECTED --> OPERATIONAL' "/tmp/$USER/beerocks/logs/beerocks_agent.log"; then
+        err "check failed"
+        exit 1
+    fi
 }
 
 usage() {
