prplmesh_utils.sh: Add roll_logs command
Currently, the roll_lof functionality is broken since it uses old beerocks_utils.sh script that is not being used anymore.

Copy roll_log function from prplmesh_utils.sh

Signed-off-by: Moran Shoeg <moranx.shoeg@intel.com>

diff --git a/common/beerocks/scripts/prplmesh_utils.sh.in b/common/beerocks/scripts/prplmesh_utils.sh.in
--- a/common/beerocks/scripts/prplmesh_utils.sh.in
+++ b/common/beerocks/scripts/prplmesh_utils.sh.in
@@ -136,6 +136,59 @@ prplmesh_delete_logs() {
     rm -rf /tmp/${SUDO_USER:-${USER}}/beerocks/logs
 }
 
+roll_logs_function()
+{
+    ROLL_PROGRESS_DIR="roll_in_progress.lock"
+    BACKUP_NAME=beerocks_logs_$(date "+%Y%m%d_%H%M%S").tar.gz
+
+    # Switch into the beerocks logs folder
+    cd @BEEROCKS_LOG_FILES_PATH@ || exit
+
+    # Check if log roll already in progress
+    if ! mkdir "$ROLL_PROGRESS_DIR"
+    then
+        echo "Roll already in progress... Exiting..."
+        exit 0
+    fi
+
+    logFiles=$(find ./*.*.log)
+    logFilesCountPreRoll=$(find ./*.*.log | wc -l)
+        
+    # Send USR1 signals to the beerocks processes to trigger log rolling
+    killall_program beerocks_controller  -USR1
+    killall_program beerocks_agent   -USR1
+    killall_program beerocks_monitor -USR1
+
+    # Wait for all the modules to create a new file
+    rollTimeout=0
+    while true; do
+        logFilesCountPostRoll=$(find ./*.*.log | wc -l)
+
+        # All modules rolled
+        if [ "$logFilesCountPostRoll" -ge $((logFilesCountPreRoll * 2)) ]; then
+            break
+        fi
+
+        # Timeout after 5 seconds
+        if [ $rollTimeout -ge 5 ]; then
+            break
+        fi
+        
+        rollTimeout=$((rollTimeout + 1))
+        sleep 1
+    done
+
+    # Pack and remove the log files
+    tar czf "$BACKUP_NAME" "$logFiles"
+    rm "$logFiles"
+
+    # Keep last 3 archives
+    rm "$(find -t ./*.tar.gz | awk 'NR>3')" > /dev/null 2>&1
+
+    # Cleanup
+    rm -r $ROLL_PROGRESS_DIR
+}
+
 start_function() {
     echo "$0: start"
     [ `id -u` -ne 0 ] && echo "$0: warning - this commands needs root privileges so might not work (are you root?)"
@@ -216,7 +269,7 @@ status_function() {
 }
 
 usage() {
-    echo "usage: $(basename $0) {start|stop|restart|status} [-hvpmdCD]"
+    echo "usage: $(basename $0) {start|stop|restart|status|roll_logs} [-hvpmdCD]"
 }
 
 main() {
@@ -261,6 +314,9 @@ main() {
             ;;
         "status")
             status_function
+            ;;
+        "roll_logs")
+            roll_logs_function
 	    return $?
             ;;
         *)
