scripts: prplmesh_utils.sh.in shellcheck fixes
During shellcheck scan of common/beerocks/scripts/prplmesh_utils.sh.in
multiple issues were raised:
Line 16,20: SC2059, SC2145 - usage of variables in printf string and
mixing array+arguments
Line 133: SC2086 - missing quotes around $SUDO_USER and $USER
Line 138,139: SC2039 - usage of local keyword which is undefined in
POSIX sh
Line 148, 151: SC2086 - missing quotes around $CURR_PIDS and
$PREV_PIDS
Line 212: SC2006 - usage of legacy backticks
Line 214: SC2050, SC2166 - usage of not well defined -a in test
statement, suspicion on constant expression
Line 215: SC2050 - suspicion on constant expression
Line 236: SC2006 - usage of legacy backticks
Line 238: SC2050, SC2166 - usage of not well defined -a in test
statement, suspicion on constant expression
Line 239: SC2050 - suspicion on constant expression
Line 283: SC2166 - usage of not well defined -a in test statement
Line 293: SC2086 - missing quotes in subshell expression
Line 297: SC2006, SC2181 - usage of legacy backticks and indirect return
code check
Line 351: SC2050 - suspicion on constant expression
Line 352: SC2086 - missing quotes around $SUDO_USER and $USER
Line 366: missing quotes around $@

In order to fix:
SC2145 - add %s and pass string as $* instead of $@
add quotes to prevent globing.
SC2086 - add quotes around variables to prevent globing.
SC2039 - remove "local"  keyword which is meaningless in POSIX sh.
SC2166 - replace "-a" occurrences with "] && [" to avoid possibility to
get into not defined case of "-a" test expression.
SC2006 - replace legacy backticks with $(..).
SC2181 - place "getopt" call in if condition to check return code
directly and avoid masking in off.
SC2050 - ignore. @VAR@ are literals which will be replaced by CMake on
configuration stage. It's not sh variables.

Signed-off-by: Anton Bilohai <a.bilohai@inango-systems.com>

diff --git a/common/beerocks/scripts/prplmesh_utils.sh.in b/common/beerocks/scripts/prplmesh_utils.sh.in
--- a/common/beerocks/scripts/prplmesh_utils.sh.in
+++ b/common/beerocks/scripts/prplmesh_utils.sh.in
@@ -13,11 +13,11 @@ dbg() {
 }
 
 err() {
-    printf '\033[1;31m'"$@\n"'\033[0m'
+    printf '\033[1;31m%s\n\033[0m' "$*"
 }
 
 success() {
-    printf '\033[1;32m'"$@\n"'\033[0m'
+    printf '\033[1;32m%s\n\033[0m' "$*"
 }
 
 run() {
@@ -39,7 +39,7 @@ platform_init() {
     base_mac=46:55:66:77
     bridge_ip=192.168.100.140
     control_ip=192.168.250.140
-    
+
     ip link add @BEEROCKS_BRIDGE_IFACE@ address "${base_mac}:00:00" type bridge
     ip link add wlan0 address "${base_mac}:00:10" type dummy
     ip link add wlan2 address "${base_mac}:00:20" type dummy
@@ -75,7 +75,7 @@ platform_deinit() {
 prplmesh_platform_db_init() {
     management_mode=${1-Multi-AP-Controller-and-Agent}
     operating_mode=${2-Gateway}
-    
+
     mkdir -p @TMP_PATH@
     {
         echo "management_mode=${management_mode}"
@@ -83,7 +83,7 @@ prplmesh_platform_db_init() {
 
         # In certification, agent must retry onboarding indefinitely
         echo "certification_mode=1"
-        echo "stop_on_failure_attempts=0" 
+        echo "stop_on_failure_attempts=0"
     } > @TMP_PATH@/prplmesh_platform_db
 }
 
@@ -130,13 +130,13 @@ prplmesh_delete_logs() {
     rm -rf @BEEROCKS_LOG_FILES_PATH@
 
     # Relevant only for Linux environment
-    rm -rf /tmp/${SUDO_USER:-${USER}}/beerocks/logs
+    rm -rf "/tmp/${SUDO_USER:-${USER}}/beerocks/logs"
 }
 
 prplmesh_watchdog() {
     # Store PIDs of the Controller and Agents
-    local CURR_PIDS="$(pgrep 'beerocks_(agent|controller)' | wc -l)"
-    local PREV_PIDS="$CURR_PIDS"
+    CURR_PIDS="$(pgrep 'beerocks_(agent|controller)' | wc -l)"
+    PREV_PIDS="$CURR_PIDS"
 
     # Make sure there's at least one PID to monitor
     if [ -z "$CURR_PIDS" ]; then
@@ -145,10 +145,10 @@ prplmesh_watchdog() {
     fi
 
     # Monitor the number of running processes
-    while [ $CURR_PIDS -ge $PREV_PIDS ]; do
+    while [ "$CURR_PIDS" -ge "$PREV_PIDS" ]; do
         sleep 1
         CURR_PIDS="$(pgrep 'beerocks_(agent|controller)' | wc -l)"
-        if [ $CURR_PIDS -gt $PREV_PIDS ]; then
+        if [ "$CURR_PIDS" -gt "$PREV_PIDS" ]; then
             PREV_PIDS=$CURR_PIDS
         fi
     done
@@ -171,7 +171,7 @@ roll_logs_function()
 
     logFiles=$(find ./*.*.log)
     logFilesCountPreRoll=$(find ./*.*.log | wc -l)
-        
+
     # Send USR1 signals to the beerocks processes to trigger log rolling
     killall_program beerocks_controller USR1
     killall_program beerocks_agent USR1
@@ -191,7 +191,7 @@ roll_logs_function()
         if [ $rollTimeout -ge 5 ]; then
             break
         fi
-        
+
         rollTimeout=$((rollTimeout + 1))
         sleep 1
     done
@@ -209,9 +209,11 @@ roll_logs_function()
 
 start_function() {
     echo "$0: start"
-    [ `id -u` -ne 0 ] && echo "$0: warning - this commands needs root privileges so might not work (are you root?)"
+    [ "$(id -u)" -ne 0 ] && echo "$0: warning - this commands needs root privileges. It might not work without them (are you root?)"
 
-    [ "@BWL_TYPE@" = "DUMMY" -a "$PLATFORM_INIT" = "true" ] && platform_init
+    # shellcheck disable=SC2050
+    [ "@BWL_TYPE@" = "DUMMY" ] && [ "$PLATFORM_INIT" = "true" ] && platform_init
+    # shellcheck disable=SC2050
     [ "@BTL_TYPE@" = "LOCAL_BUS" ] && prplmesh_framework_init
     case "$PRPLMESH_MODE" in
         CA | ca)
@@ -233,9 +235,11 @@ start_function() {
 
 stop_function() {
     echo "$0: stop"
-    [ `id -u` -ne 0 ] && echo "$0: warning - this commands needs root privileges so might not work (are you root?)"
+    [ "$(id -u)" -ne 0 ] && echo "$0: warning - this commands needs root privileges. It might not work without them (are you root?)"
 
-    [ "@BWL_TYPE@" = "DUMMY" -a "$PLATFORM_INIT" = "true" ] && platform_deinit
+    # shellcheck disable=SC2050
+    [ "@BWL_TYPE@" = "DUMMY" ] && [ "$PLATFORM_INIT" = "true" ] && platform_deinit
+    # shellcheck disable=SC2050
     [ "@BTL_TYPE@" = "LOCAL_BUS" ] && prplmesh_framework_deinit
     prplmesh_controller_stop
     prplmesh_agent_stop
@@ -243,7 +247,7 @@ stop_function() {
 }
 
 # Note: Apparently on some Linux version space is added to the process name.
-# Therefore added "($|[[:blank:]])" to the end of the regex expression which means the end of the 
+# Therefore added "($|[[:blank:]])" to the end of the regex expression which means the end of the
 # line ($) or blank character ([[:blank:]])
 main_agent_operational() {
     pgrep -fx "@INSTALL_PATH@/bin/beerocks_agent($|[[:blank:]])" > /dev/null 2>&1 || return 1
@@ -280,7 +284,7 @@ status_function() {
     report "@BEEROCKS_WLAN1_IFACE@ radio agent operational" radio_agent_operational $LOGS_PATH @BEEROCKS_WLAN1_IFACE@
     report "@BEEROCKS_WLAN2_IFACE@ radio agent operational" radio_agent_operational $LOGS_PATH @BEEROCKS_WLAN2_IFACE@
 
-    [ "$VERBOSE" = "true" -a $error = 1 ] && {
+    [ "$VERBOSE" = "true" ] && [  $error = 1 ] && {
         cat $LOGS_PATH/beerocks_agent@BEEROCKS_LOG_FILES_SUFFIX@
         cat $LOGS_PATH/beerocks_agent_@BEEROCKS_WLAN1_IFACE@@BEEROCKS_LOG_FILES_SUFFIX@
         cat $LOGS_PATH/beerocks_agent_@BEEROCKS_WLAN2_IFACE@@BEEROCKS_LOG_FILES_SUFFIX@
@@ -290,15 +294,17 @@ status_function() {
 }
 
 usage() {
-    echo "usage: $(basename $0) {start|stop|restart|status|roll_logs} [-hvpmdCD]"
+    echo "usage: $(basename "$0") {start|stop|restart|status|roll_logs} [-hvpmdCD]"
 }
 
 main() {
-    OPTS=`getopt -o 'hvm:pdC:D:'  -n 'parse-options' \
+    if ! OPTS=$(getopt -o 'hvm:pdC:D:'  -n 'parse-options' \
         --long 'verbose,help,mode:,platform-init,delete-logs,iface-ctrl,iface-data' \
-        -- "$@"`
-
-    if [ $? != 0 ] ; then err "Failed parsing options." >&2 ; usage; exit 1 ; fi
+        -- "$@") ; then
+            err "Failed parsing options." >&2
+            usage
+            exit 1
+    fi
 
     eval set -- "$OPTS"
 
@@ -348,8 +354,9 @@ main() {
     esac
 
     # Give write permissions (linux only)
+    # shellcheck disable=SC2050
     if [ "@TARGET_PLATFORM@" = "linux" ]; then
-        chmod -R +o+w /tmp/${SUDO_USER:-${USER}}
+        chmod -R +o+w "/tmp/${SUDO_USER:-${USER}}"
     fi
 }
 
@@ -363,4 +370,4 @@ PRPLMESH_MODE="CA" # CA = Controller & Agent, A = Agent only, C = Controller onl
 # Export MultiAP libs folder
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:@INSTALL_PATH@/lib
 
-main $@
+main "$@"
